name: "Dependabot: GitHub Actions"

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Dependabot for GitHub Actions
        uses: dependabot/fetch-metadata@v2
        with:
          package-ecosystem: "github-actions"
          directory: "/"
          schedule: "weekly"
